# # █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Opacity
# windowrule = match:class ^(Brave-browser)$, opacity 0.90 0.90
windowrule = match:class ^(Steam)$, opacity 0.80 0.80
windowrule = match:class ^(steam)$, opacity 0.80 0.80
windowrule = match:class ^(steamwebhelper)$, opacity 0.80 0.80
windowrule = match:class ^(Spotify)$, opacity 0.80 0.80
windowrule = match:class ^(Code)$, opacity 0.80 0.80
windowrule = match:class ^(kitty)$, opacity 0.85 0.70
windowrule = match:class ^(thunar)$, opacity 0.80 0.80
windowrule = match:class ^(file-roller)$, opacity 0.80 0.80
windowrule = match:class ^(nwg-look)$, opacity 0.80 0.80
windowrule = match:class ^(qt5ct)$, opacity 0.80 0.80
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, opacity 0.80 0.70

# Floating windows
windowrule = match:class ^(org.kde.polkit-kde-authentication-agent-1)$, float 1
windowrule = match:class ^(pavucontrol)$, float 1
windowrule = match:title ^(Media viewer)$, float 1
windowrule = match:title ^(Volume Control)$, float 1
windowrule = match:title ^(Picture-in-Picture)$, float 1
windowrule = match:class ^(Viewnior)$, float 1
windowrule = match:title ^(DevTools)$, float 1
windowrule = match:class ^(file_progress)$, float 1
windowrule = match:class ^(confirm)$, float 1
windowrule = match:class ^(dialog)$, float 1
windowrule = match:class ^(download)$, float 1
windowrule = match:class ^(notification)$, float 1
windowrule = match:class ^(error)$, float 1
windowrule = match:class ^(confirmreset)$, float 1
windowrule = match:title ^(Open File)$, float 1
windowrule = match:title ^(branchdialog)$, float 1
windowrule = match:title ^(Confirm to replace files)$, float 1
windowrule = match:title ^(File Operation Progress)$, float 1
windowrule = match:class ^(Rofi)$, float 1

# Move
windowrule = match:title ^(Volume Control)$, move 75 44%

# Workspace
windowrule = match:class ^(Brave-browser)$, workspace 1
windowrule = match:class ^(discord)$, workspace 4

# Size
windowrule = match:class ^(download)$, size 800 600
windowrule = match:title ^(Open File)$, size 800 600
windowrule = match:title ^(Save File)$, size 800 600
windowrule = match:title ^(Volume Control)$, size 800 600

# xwaylandvideobridge
windowrule = match:class ^(xwaylandvideobridge)$, opacity 0.0 override 0.0 override
